stages:
  - test
  - infrastructure
  - deploy
  - destroy

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

infrastructure:
  stage: infrastructure
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  tags:
    - aws-runner
  script:
    - cd terraform
    - terraform init
    - terraform plan -out=tfplan
    - terraform apply -auto-approve tfplan

    - echo "EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip)" >> ../deploy.env
    - echo "DB_HOST=$(terraform output -raw db_host)" >> ../deploy.env
    - echo "DB_PORT=$(terraform output -raw db_port)" >> ../deploy.env
    - echo "DB_NAME=$(terraform output -raw db_name)" >> ../deploy.env
    - echo "DB_USERNAME=${TF_VAR_db_username}" >> ../deploy.env
    - echo "DB_PASSWORD=${TF_VAR_db_password}" >> ../deploy.env
  artifacts:
    reports:
      dotenv: deploy.env

destroy_infra:
  stage: destroy
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
  tags:
    - aws-runner
  needs: []
  script:
    - cd terraform
    - terraform init
    - terraform destroy -auto-approve
