[flyway]
locations = ["filesystem:./data", "filesystem:./migrations", "filesystem:./programmability"]

[environments.default]
url = "jdbc:postgresql://localhost:5432/codenames"                              
user = "codenames"
password = "codenames"