CREATE USER "${db_user}" WITH PASSWORD '${db_user_password}';

GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO "${db_user}";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "${db_user}";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE ON TABLES TO "${db_user}";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO "${db_user}";
